version: '3.1'

services:

  ocr-rest:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - LC_ALL=C
      - TESSDATA_PREFIX=/usr/share/tessdata
    depends_on:
      - mongo
    links:
      - mongo  
