spring.datasource:
  url: ${{ secrets.DB_URL }}
  username: ${{ secrets.DB_USERNAME }}
  password: ${{ secrets.DB_PASSWORD }}
spring.jpa:
  properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB