spring.datasource:
  url: jdbc:postgresql://ec2-13-125-191-192.ap-northeast-2.compute.amazonaws.com:5432/postgres
  username: postgres
  password: rlaxodid23!
spring.jpa:
  properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB